### ISSUE TITLE
Webview Active Check Prevents Command Execution

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-sprotty/sprotty-vscode#31]
I am using a `sprotty-vscode`-based plugin in a [Theia](https://github.com/eclipse-theia/theia) application, and I find that the [`.diagram.fit` and `.diagram.center` commands](https://github.com/eclipse/sprotty-vscode/blob/6f3693049585202f9f68d719529b45b7db67c997/sprotty-vscode-extension/src/sprotty-vscode-extension.ts#L50-L69) are frequently (but not always) prevented from running because the [`findActiveWebview` method](https://github.com/eclipse/sprotty-vscode/blob/6f3693049585202f9f68d719529b45b7db67c997/sprotty-vscode-extension/src/sprotty-vscode-extension.ts#L80-L86) inappropriately fails to identify the active webview if the command is triggered via the command palette. Theia has [logic](https://github.com/eclipse-theia/theia/blob/0a721961ac7e8599284afc51e69c7e067f50d74f/packages/core/src/browser/quick-open/quick-command-service.ts#L248-L254) that restores focus to the webview, but the webview's state is checked before the refocus is registered. The following screenshot shows the output of a log during the `findActiveWebview` check, and one timed out by one second:

![image](https://user-images.githubusercontent.com/62660806/100671297-e1cc4800-3325-11eb-970a-b8c925badf88.png)

This screenshot shows that Theia correctly identifies the webview `iframe` as the active element, and that before the command is dispatched to Sprotty, a check for `window.document.activeElement === this.activeElement` (i.e. that focus has been restored to the `iframe`) passes.

![image](https://user-images.githubusercontent.com/62660806/100671686-7f277c00-3326-11eb-9f3b-2e09e400abcb.png)

I will cross-post an issue for Theia, since it may be an artifact of their command system.

**Comment by colin-grant-work** [comment]
Posted as Theia issue [here](https://github.com/eclipse-theia/theia/issues/8808).

**Comment by spoenemann** [comment]
Closing due to https://github.com/eclipse-theia/theia/issues/8808#issuecomment-977053259
