### ISSUE TITLE
Unable to load model in the non-language-server case

### ISSUE THREAD

**Issue by agiledigits** [eclipse-sprotty/sprotty-vscode#34]
I'm trying to use the sprotty diagram in a VSCode extension that doesn't involve a language server. Basically I don't want to add a new DSL; instead the model is loaded from a JSON/YAML object (persisted as a file in the workspace). 

I implemented my own `SprottyVscodeExtension` and `SprottyStarter`, and implemented the webview according to the class diagram example  from sprotty. However there's only an empty diagram when I select "Open in Diagram". It turns out that the webview gets loaded correctly but the model is "EMPTY". 

Looking into the implementation of `SprottyStarter`, I can see that the ModelSource is provided by `VscodeDiagramServer`:
`container.bind(TYPES.ModelSource).toService(VscodeDiagramServer);`

Doesn't this mean that the diagram is expected to be served from the language server? I don't see any code in sprotty-vscode that loads the model from a file in the workspace, and I have yet to find a working example that shows how this is achieved without a language server. I don't mind implementing a custom "loader", but I just don't see a way to invoke it.

**Comment by spoenemann** [comment]
> Doesn't this mean that the diagram is expected to be served from the language server?

No, it just means that the default is to provide the diagram from the backend of the VS Code extension. We just released a new package `sprotty-protocol` that can be used in the backend (main extension code), but it's true that an example for this is missing. I hope we can provide one soon.

If you want to create the model directly in the frontend (webview), you can rebind `TYPES.ModelSource` to `LocalModelSource`.

**Comment by zam1kor** [comment]
is there any update regarding this topic?

**Comment by spoenemann** [comment]
Please check out [v0.5.0](https://github.com/eclipse/sprotty-vscode/releases/tag/v0.5.0). It brings a major redesign of the API. This includes an option for the new `WebviewEndpoint` class to communicate via a `DiagramServer` as defined in [sprotty-protocol](https://github.com/eclipse/sprotty/blob/master/packages/sprotty-protocol/src/diagram-server.ts):

https://github.com/eclipse/sprotty-vscode/blob/fa9c9ac4cc36960208ea732d22fc0904d4fcd5b2/packages/sprotty-vscode/src/webview-endpoint.ts#L47

You can create this `DiagramServer` in the VS Code extension to generate diagrams and handle client actions.

**Comment by christianmalek** [comment]
Hi, is there an example for the usage of `DiagramServer` and `WebviewEndpoint` available yet?

**Comment by spoenemann** [comment]
I don't know of a publicly available example. But something like this could be a good start:
```typescript
export class StatesWPM extends WebviewPanelManager {

    protected override createEndpoint(identifier: SprottyDiagramIdentifier): WebviewEndpoint {
        const webviewContainer = this.createWebview(identifier);
        const participant = this.messenger.registerWebviewPanel(webviewContainer);
        const diagramServices: DiagramServices = {
            DiagramGenerator: new StatesDiagramGenerator()
        };
        return new WebviewEndpoint({
            webviewContainer,
            messenger: this.messenger,
            messageParticipant: participant,
            identifier,
            diagramServerFactory: (dispatch) => new DiagramServer(dispatch, diagramServices)
        });
    }

}

export class StatesDiagramGenerator implements IDiagramGenerator {
    generate(args: GeneratorArguments): SModelRoot | Promise<SModelRoot> {
        // Generate a diagram model based on options like `args.options.sourceUri`
    }
}
```

**Comment by christianmalek** [comment]
I appreciate it. Thank you for the fast response!
