### ISSUE TITLE
sprotty (diagram &text) synchronized 

### ISSUE THREAD

**Issue by zrwsmd** [eclipse-sprotty/sprotty-vscode#93]
why my colleague local sprotty project can achieve when diagram changed(right part),corresponding left part also synchronized change,i found new project(sprotty-vscode-master) can not synchronized since right part is readonly .he once used old sprotty-vscode project without langium module few years ago,only have xtext module,it is because xtext can achieve it?desperately for your answer,thanks ahead
![image](https://github.com/eclipse-sprotty/sprotty-vscode/assets/26995040/0b53769f-a60f-42b2-a5ab-c87fadcf1232)

**Comment by spoenemann** [comment]
We simply haven't implemented the editing features in the Langium-based example yet. But it's totally possible to do the same as we did with Xtext.

**Comment by zrwsmd** [comment]
i see the difference is old project export class StatesSprottyStarter and then Compiled into JavaScript,then it works,am i right?also ,the code(delete-with-workspace-edit.ts) is a little confused,like shouldDelete method and isTraceable method,for shouldDelete method,which condition 
 element do not have 'selectFeature',and for isTraceable method,i totally did catch it meaning

**Comment by zrwsmd** [comment]
how xtext-based example  achieved this,i see slightly different between Langium-based example and xtext-based example

**Comment by zrwsmd** [comment]
how xtext-based example achieved this,i see slightly different between Langium-based example and xtext-based example

**Comment by zrwsmd** [comment]
how it achieved  when right part change,left part changed too,like you said code is in  https://github.com/eclipse-sprotty/sprotty-vscode/blob/master/packages/sprotty-vscode-webview/src/lsp/editing/delete-with-workspace-edit.ts.but i just did not understand the code,can you briefly describe how it worked

**Comment by spoenemann** [comment]
The WorkspaceEdit that is created in that code replaces the text region of the selected element with an empty string, which results in the deletion of that element.
